colors:
  bright:
    black: '0x002b36'
    blue: '0x839496'
    cyan: '0x93a1a1'
    green: '0x586e75'
    magenta: '0x6c71c4'
    red: '0xcb4b16'
    white: '0xfdf6e3'
    yellow: '0x657b83'
  cursor:
    cursor: '0x859900'
    text: '0x002b36'
  normal:
    black: '0x073642'
    blue: '0x268bd2'
    cyan: '0x2aa198'
    green: '0x859900'
    magenta: '0xd33682'
    red: '0xdc322f'
    white: '0xeee8d5'
    yellow: '0xb58900'
  primary:
    background: '0xfdf6e3'
    foreground: '0x586e75'
cursor:
  style:
    blinking: Always
  blink_interval: 600
  unfocused_hollow: true
dynamic_title: true
env:
  TERM: alacritty
font:
  bold:
    family: UbuntuMono
    style: Bold
  bold_italic:
    family: UbuntuMono
    style: Bold Italic
  italic:
    family: UbuntuMono
    style: Italic
  normal:
    family: UbuntuMono
    style: Regular
  size: 12.0
hints:
  alphabet: jfkdls;ahgurieowpq
  enabled:
  - binding:
      key: U
      mods: Control|Shift
    command: xdg-open
    mouse:
      enabled: true
      mods: None
    post_processing: true
    regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\0\
      -\x1F\x7F-\x9F<>\"\\s{-}\\^\u27E8\u27E9`]+"
  - binding:
      key: Y
      mods: Control|Shift
    command: Copy
    post_processing: false
    regex: '[a-z0-9_-]+'
key_bindings:
- action: Paste
  key: V
  mods: Control|Shift
- action: Copy
  key: C
  mods: Control|Shift
- action: ResetFontSize
  key: Key0
  mods: Control
- action: IncreaseFontSize
  key: Plus
  mods: Control
- action: DecreaseFontSize
  key: Minus
  mods: Control
- action: ScrollPageDown
  key: K
  mods: Control|Shift
- action: ScrollPageUp
  key: L
  mods: Control|Shift
live_config_reload: true
scrolling:
  history: 100000
window:
  class:
    general: Alacritty
    instance: Alacritty
  gtk_theme_variant: light
  padding:
    x: 1
    y: 1
  title: Alacritty
