colors:
  bright:
    black: '0xd5cdb6'
    blue: '0x006dce'
    cyan: '0x00978a'
    green: '0x428b00'
    magenta: '0xc44392'
    red: '0xcc1729'
    white: '0x3a4d53'
    yellow: '0xa78300'
  normal:
    black: '0xece3cc'
    blue: '0x0072d4'
    cyan: '0x009c8f'
    green: '0x489100'
    magenta: '0xca4898'
    red: '0xd2212d'
    white: '0x909995'
    yellow: '0xad8900'
  primary:
    background: '0xfbf3db'
    foreground: '0x53676d'
cursor:
  blink_interval: 600
  style:
    blinking: Always
  unfocused_hollow: true
dynamic_title: true
env:
  TERM: alacritty
font:
  bold:
    family: UbuntuMono
    style: Bold
  bold_italic:
    family: UbuntuMono
    style: Bold Italic
  italic:
    family: UbuntuMono
    style: Italic
  normal:
    family: UbuntuMono
    style: Regular
  size: 18
hints:
  alphabet: jfkdls;ahgurieowpq
  enabled:
  - binding:
      key: U
      mods: Control|Shift
    command: xdg-open
    mouse:
      enabled: true
      mods: None
    post_processing: true
    regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\0\
      -\x1F\x7F-\x9F<>\"\\s{-}\\^\u27E8\u27E9`]+"
  - binding:
      key: Y
      mods: Control|Shift
    command: Copy
    post_processing: false
    regex: '[a-z0-9_-]+'
key_bindings:
- action: Paste
  key: V
  mods: Control|Shift
- action: Copy
  key: C
  mods: Control|Shift
- action: ResetFontSize
  key: Key0
  mods: Control
- action: IncreaseFontSize
  key: Plus
  mods: Control
- action: DecreaseFontSize
  key: Minus
  mods: Control
- action: ScrollPageDown
  key: K
  mods: Control|Shift
- action: ScrollPageUp
  key: L
  mods: Control|Shift
live_config_reload: true
mouse_bindings:
- action: PasteSelection
  mouse: Middle
- action: CopySelection
  mouse: Right
scrolling:
  history: 100000
window:
  class:
    general: Alacritty
    instance: Alacritty
  decorations_theme_variant: Light
  padding:
    x: 1
    y: 1
  title: Alacritty
