# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  TERM: alacritty

window:
  padding:
    x: 1
    y: 1

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

  gtk_theme_variant: light

scrolling:
  history: 100000

font:
  normal:
    family: UbuntuMono
    style: Regular

  bold:
    family: UbuntuMono
    style: Bold

  italic:
    family: UbuntuMono
    style: Italic

  bold_italic:
    family: UbuntuMono
    style: Bold Italic

  size: 12.0

# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    background: '0xfdf6e3'
    foreground: '0x586e75'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x002b36'
    cursor: '0x859900'

  # Normal colors
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'

dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

hints:
  alphabet: "jfkdls;ahgurieowpq"
  enabled:
  - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    command: xdg-open
    post_processing: true
    mouse:
      enabled: true
      mods: None
    binding:
      key: U
      mods: Control|Shift
  - regex: "[a-z0-9_-]+"
    command: Copy
    post_processing: false
    binding:
      key: Y
      mods: Control|Shift

key_bindings:
#     # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
#   - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: K,      mods: Control|Shift,       action: ScrollPageDown }
  - { key: L,    mods: Control|Shift,       action: ScrollPageUp }

#   - { key: Paste,                    action: Paste                            }
#   - { key: Copy,                     action: Copy                             }
#   - { key: L,         mods: Control, action: ClearLogNotice                   }
#   - { key: L,         mods: Control, chars: "\x0c"                            }
#   - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
#   - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
#   - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
#   - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
