colors:
  bright:
    black: '0x2d5b69'
    blue: '0x58a3ff'
    cyan: '0x53d6c7'
    green: '0x84c747'
    magenta: '0xff84cd'
    red: '0xff665c'
    white: '0xcad8d9'
    yellow: '0xebc13d'
  normal:
    black: '0x184956'
    blue: '0x4695f7'
    cyan: '0x41c7b9'
    green: '0x75b938'
    magenta: '0xf275be'
    red: '0xfa5750'
    white: '0x72898f'
    yellow: '0xdbb32d'
  primary:
    background: '0x103c48'
    foreground: '0xadbcbc'
cursor:
  blink_interval: 600
  style:
    blinking: Always
  unfocused_hollow: true
dynamic_title: true
env:
  TERM: alacritty
font:
  bold:
    family: UbuntuMono
    style: Bold
  bold_italic:
    family: UbuntuMono
    style: Bold Italic
  italic:
    family: UbuntuMono
    style: Italic
  normal:
    family: UbuntuMono
    style: Regular
  size: 14
hints:
  alphabet: jfkdls;ahgurieowpq
  enabled:
  - binding:
      key: U
      mods: Control|Shift
    command: xdg-open
    mouse:
      enabled: true
      mods: None
    post_processing: true
    regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\0\
      -\x1F\x7F-\x9F<>\"\\s{-}\\^\u27E8\u27E9`]+"
  - binding:
      key: Y
      mods: Control|Shift
    command: Copy
    post_processing: false
    regex: '[a-z0-9_-]+'
key_bindings:
- action: Paste
  key: V
  mods: Control|Shift
- action: Copy
  key: C
  mods: Control|Shift
- action: ResetFontSize
  key: Key0
  mods: Control
- action: IncreaseFontSize
  key: Plus
  mods: Control
- action: DecreaseFontSize
  key: Minus
  mods: Control
- action: ScrollPageDown
  key: K
  mods: Control|Shift
- action: ScrollPageUp
  key: L
  mods: Control|Shift
live_config_reload: true
mouse_bindings:
- action: PasteSelection
  mouse: Middle
- action: CopySelection
  mouse: Right
scrolling:
  history: 100000
window:
  class:
    general: Alacritty
    instance: Alacritty
  decorations_theme_variant: Light
  padding:
    x: 1
    y: 1
  title: Alacritty
