#!/bin/bash
echo -e "$HOME/bin/dark_theme
$HOME/bin/light_theme
$HOME/.screenlayout/laptop.sh
$HOME/.screenlayout/narrow.sh
$HOME/.screenlayout/wide.sh
$HOME/scripts/float-laptop-inputs
$HOME/scripts/reattach-laptop-inputs" | rofi -dmenu -lines 7 -font "Ubuntu 25" | sh
