#!/bin/bash
echo -e "$HOME/bin/dark-gruv
$HOME/bin/light-gruv
$HOME/bin/dark-sele
$HOME/bin/light-sele
$HOME/.screenlayout/laptop.sh
$HOME/.screenlayout/narrow.sh
$HOME/.screenlayout/wide.sh
$HOME/.screenlayout/home.sh
$HOME/scripts/float-laptop-inputs
$HOME/scripts/reattach-laptop-inputs
$HOME/bin/small-font
$HOME/bin/middle-font
$HOME/bin/big-font
$HOME/bin/huge-font" | rofi -dmenu -lines 15 -font "Ubuntu 25" | sh
