set $bg_main    #fbf1c7
set $bg_alt     #ebdbb2
set $title_fg   #3c3836
set $fg_main    #7c6f64
set $fg_dim     #bdae93
set $accent     #79740e
set $accent_fg  #fbf1c7
set $indicator   #8f3f71
set $indicator_i #ebdbb2
set $sep         #bdae93
set $info       #076678
set $info_fg    #fbf1c7
set $urgent     #b16286
set $urgent_fg  #fbf1c7
set $urgent_ind #9d0006
set $warn       #af3a03
set $warn_fg    #fbf1c7

client.focused          $accent $accent $accent_fg $indicator
client.focused_inactive $bg_alt $bg_alt $title_fg  $indicator_i
client.unfocused        $bg_alt $bg_alt $fg_main   $sep
client.urgent           $urgent $urgent $urgent_fg $urgent_ind

bar {
    status_command i3blocks
    position top
    font pango:Terminess Nerd Font 14
    tray_output primary
    tray_padding 4
    strip_workspace_numbers yes

    colors {
        background $bg_main
        statusline $fg_main
        separator  $sep

        focused_workspace  $accent  $accent  $accent_fg
        active_workspace   $info    $info    $info_fg
        inactive_workspace $bg_main $bg_main $fg_dim
        urgent_workspace   $urgent  $urgent  $urgent_fg
        binding_mode       $warn    $warn    $warn_fg
    }
}
