set $bg_main    #282828
set $bg_alt     #3c3836
set $title_fg   #ebdbb2
set $fg_main    #a89984
set $fg_dim     #7c6f64
set $accent     #98971a
set $accent_fg  #fbf1c7
set $indicator   #b16286
set $indicator_i #b16286
set $sep         #504945
set $info       #458588
set $info_fg    #fbf1c7
set $urgent     #d3869b
set $urgent_fg  #282828
set $urgent_ind #cc241d
set $warn       #d65d0e
set $warn_fg    #282828

client.focused          $accent $accent $accent_fg $indicator
client.focused_inactive $bg_alt $bg_alt $title_fg  $indicator_i
client.unfocused        $bg_alt $bg_alt $fg_main   $sep
client.urgent           $urgent $urgent $urgent_fg $urgent_ind

bar {
    status_command i3blocks
    position top
    font pango:Terminess Nerd Font 14
    tray_output primary
    tray_padding 4
    strip_workspace_numbers yes

    colors {
        background $bg_main
        statusline $fg_main
        separator  $sep

        focused_workspace  $accent  $accent  $accent_fg
        active_workspace   $info    $info    $info_fg
        inactive_workspace $bg_main $bg_main $fg_dim
        urgent_workspace   $urgent  $urgent  $urgent_fg
        binding_mode       $warn    $warn    $warn_fg
    }
}
