set $bg_main     #fdf6e3
set $bg_alt      #EEEEEE
set $title_fg    #888888
set $fg_main     #888888
set $fg_dim      #93a1a1
set $accent      #859900
set $accent_fg   #fdf6e3
set $indicator   #6c71c4
set $indicator_i #EEEEEE
set $sep         #292d2e
set $info        #268bd2
set $info_fg     #fdf6e3
set $urgent      #d33682
set $urgent_fg   #fdf6e3
set $urgent_ind  #dc322f
set $warn        #cb4b16
set $warn_fg     #fdf6e3

client.focused          $accent $accent $accent_fg $indicator
client.focused_inactive $bg_alt $bg_alt $title_fg  $indicator_i
client.unfocused        $bg_alt $bg_alt $fg_main   $sep
client.urgent           $urgent $urgent $urgent_fg $urgent_ind

bar {
    status_command i3blocks
    position top
    font pango:Terminess Nerd Font 14
    tray_output primary
    tray_padding 4
    strip_workspace_numbers yes

    colors {
        background $bg_main
        statusline $fg_main
        separator  $sep

        focused_workspace  $accent  $accent  $accent_fg
        active_workspace   $info    $info    $info_fg
        inactive_workspace $bg_main $bg_main $fg_dim
        urgent_workspace   $urgent  $urgent  $urgent_fg
        binding_mode       $warn    $warn    $warn_fg
    }
}
